/*
 * sensord
 *
 * Copyright (c) 2016 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef _SENSOR_TYPES_H_
#define _SENSOR_TYPES_H_

#include "enum_factory.h"

#ifdef __cplusplus
extern "C"
{
#endif

#define SENSOR_TYPE(DEF_SENSOR, DEF_SENSOR_VALUE) \
	DEF_SENSOR_VALUE(UNKNOWN_SENSOR, -2) \
	DEF_SENSOR_VALUE(ALL_SENSOR, -1) \
	DEF_SENSOR_VALUE(ACCELEROMETER_SENSOR, 0) \
	DEF_SENSOR(GRAVITY_SENSOR) \
	DEF_SENSOR(LINEAR_ACCEL_SENSOR) \
	DEF_SENSOR(GEOMAGNETIC_SENSOR) \
	DEF_SENSOR(ROTATION_VECTOR_SENSOR) \
	DEF_SENSOR(ORIENTATION_SENSOR) \
	DEF_SENSOR(GYROSCOPE_SENSOR) \
	DEF_SENSOR(LIGHT_SENSOR) \
	DEF_SENSOR(PROXIMITY_SENSOR) \
	DEF_SENSOR(PRESSURE_SENSOR) \
	DEF_SENSOR(ULTRAVIOLET_SENSOR) \
	DEF_SENSOR(TEMPERATURE_SENSOR) \
	DEF_SENSOR(HUMIDITY_SENSOR) \
	DEF_SENSOR(HRM_SENSOR) \
	DEF_SENSOR(HRM_LED_GREEN_SENSOR) \
	DEF_SENSOR(HRM_LED_IR_SENSOR) \
	DEF_SENSOR(HRM_LED_RED_SENSOR) \
	DEF_SENSOR(GYROSCOPE_UNCAL_SENSOR) \
	DEF_SENSOR(GEOMAGNETIC_UNCAL_SENSOR) \
	DEF_SENSOR(GYROSCOPE_RV_SENSOR) \
	DEF_SENSOR(GEOMAGNETIC_RV_SENSOR) \
	\
	DEF_SENSOR_VALUE(HUMAN_PEDOMETER_SENSOR, 0x300) \
	DEF_SENSOR(HUMAN_SLEEP_MONITOR_SENSOR) \
	DEF_SENSOR(HUMAN_SLEEP_DETECTOR_SENSOR) \
	DEF_SENSOR(HUMAN_STRESS_MONITOR_SENSOR) \
	\
	DEF_SENSOR_VALUE(EXERCISE_WALKING_SENSOR, 0x400) \
	DEF_SENSOR(EXERCISE_RUNNING_SENSOR) \
	DEF_SENSOR(EXERCISE_HIKING_SENSOR) \
	DEF_SENSOR(EXERCISE_CYCLING_SENSOR) \
	DEF_SENSOR(EXERCISE_ELLIPTICAL_SENSOR) \
	DEF_SENSOR(EXERCISE_INDOOR_CYCLING_SENSOR) \
	DEF_SENSOR(EXERCISE_ROWING_SENSOR) \
	DEF_SENSOR(EXERCISE_STEPPER_SENSOR) \
	\
	DEF_SENSOR_VALUE(FUSION_SENSOR, 0x900) \
	DEF_SENSOR(AUTO_ROTATION_SENSOR) \
	DEF_SENSOR(AUTO_BRIGHTNESS_SENSOR) \
	\
	DEF_SENSOR_VALUE(GESTURE_MOVEMENT_SENSOR, 0x1200) \
	DEF_SENSOR(GESTURE_WRIST_UP_SENSOR) \
	DEF_SENSOR(GESTURE_WRIST_DOWN_SENSOR) \
	DEF_SENSOR(GESTURE_MOVEMENT_STATE_SENSOR) \
	DEF_SENSOR(GESTURE_FACE_DOWN_SENSOR) \
	\
	DEF_SENSOR_VALUE(ACTIVITY_TRACKER_SENSOR, 0x1A00) \
	DEF_SENSOR(ACTIVITY_LEVEL_MONITOR_SENSOR) \
	DEF_SENSOR(GPS_BATCH_SENSOR) \
	\
	DEF_SENSOR_VALUE(HRM_CTRL_SENSOR, 0x1A80) \
	\
	DEF_SENSOR_VALUE(WEAR_STATUS_SENSOR, 0x2000) \
	DEF_SENSOR(WEAR_ON_MONITOR_SENSOR) \
	DEF_SENSOR(NO_MOVE_DETECTOR_SENSOR) \
	DEF_SENSOR(RESTING_HR_SENSOR) \
	DEF_SENSOR(STEP_LEVEL_MONITOR_SENSOR) \
	DEF_SENSOR(EXERCISE_STANDALONE_SENSOR) \
	DEF_SENSOR(EXERCISE_HR_SENSOR) \
	DEF_SENSOR(WORKOUT_SENSOR) \
	DEF_SENSOR(CYCLE_MONITOR_SENSOR) \
	DEF_SENSOR(STAIR_TRACKER_SENSOR) \
	\
	DEF_SENSOR_VALUE(CONTEXT_SENSOR, 0x7000) \
	DEF_SENSOR(MOTION_SENSOR) \
	DEF_SENSOR(PIR_SENSOR) \
	DEF_SENSOR(PIR_LONG_SENSOR) \
	DEF_SENSOR(DUST_SENSOR) \
	DEF_SENSOR(THERMOMETER_SENSOR) \
	DEF_SENSOR(PEDOMETER_SENSOR) \
	DEF_SENSOR(FLAT_SENSOR) \
	DEF_SENSOR(HRM_RAW_SENSOR) \
	DEF_SENSOR(TILT_SENSOR) \
	DEF_SENSOR(RV_RAW_SENSOR) \

#define BIO_HRM_SENSOR              HRM_SENSOR
#define BIO_LED_GREEN_SENSOR        HRM_LED_GREEN_SENSOR
#define BIO_LED_IR_SENSOR           HRM_LED_IR_SENSOR
#define BIO_LED_RED_SENSOR          HRM_LED_RED_SENSOR
#define BIO_SENSOR                  HRM_RAW_SENSOR
#define SLEEP_DETECTOR_SENSOR       HUMAN_SLEEP_DETECTOR_SENSOR
#define STRESS_MONITOR_SENSOR       HUMAN_STRESS_MONITOR_SENSOR
#define AUTOSESSION_EXERCISE_SENSOR WORKOUT_SENSOR
#define EXERCISE_COACH_SENSOR       EXERCISE_STANDALONE_SENSOR

DECLARE_SENSOR_ENUM(sensor_type_t, SENSOR_TYPE)

enum proxi_change_state {
	PROXIMITY_STATE_NEAR = 0,
	PROXIMITY_STATE_FAR = 1,
};

enum auto_rotation_state {
	AUTO_ROTATION_DEGREE_UNKNOWN = 0,
	AUTO_ROTATION_DEGREE_0,
	AUTO_ROTATION_DEGREE_90,
	AUTO_ROTATION_DEGREE_180,
	AUTO_ROTATION_DEGREE_270,
};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
DECLARE_SENSOR_ENUM_UTIL_NS(sensor_type_t)
#endif

#include <sensor_deprecated.h>

#endif /* _SENSOR_TYPES_H_ */
